sudo: true
language: haskell

git:
  depth: 5

cabal: "3.0"

cache:
  directories:
    - "$HOME/.cabal/store"

matrix:
  include:
    - ghc: 8.6.5
    - ghc: 8.8.1

install:
  # HLint check
  - curl -sSL https://raw.github.com/ndmitchell/neil/master/misc/travis.sh | sh -s -- hlint 'benchmark/'
  - cabal update
  - cabal build --enable-tests --enable-benchmarks

script:
  - cabal bench --enable-benchmarks

notifications:
  email: false
